apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: hwd-app-alert-routing
  namespace: monitoring
  labels:
    release: prometheus
spec:
  route:
    groupBy: ["alertname", "severity", "namespace"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 2h
    receiver: local-null
  receivers:
    - name: local-null
