apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hwd-app-monitor
  namespace: monitoring
  labels:
    release: prometheus # Needs to match prometheus operator label selector
spec:
  selector:
    matchLabels:
      app: hwd-app
  namespaceSelector:
    any: true
  endpoints:
  - port: web
    path: /metrics
    interval: 15s
